### ISSUE TITLE
ModuleNotFoundError: No module named 'surrogate_models'

### ISSUE THREAD

**Issue by lcmeng** [naszilla/naszilla#20]
Hi,

I followed the installation steps and tried the first test `python naszilla/run_experiments.py --search_space nasbench_101 --algo_params all_algos --queries 30 --trials 1`. However, it resulted in `ModuleNotFoundError`. 

```
Traceback (most recent call last):
  File "naszilla/run_experiments.py", line 11, in <module>
    from naszilla.nas_benchmarks import Nasbench101, Nasbench201, Nasbench301
  File "/home/ubuntu/naszilla/naszilla/nas_benchmarks.py", line 8, in <module>
    import nasbench301 as nb
  File "/home/ubuntu/naszilla/src/nasbench301/nasbench301/__init__.py", line 1, in <module>
    from nasbench301.api import load_ensemble
  File "/home/ubuntu/naszilla/src/nasbench301/nasbench301/api.py", line 6, in <module>
    from nasbench301.surrogate_models import utils
  File "/home/ubuntu/naszilla/src/nasbench301/nasbench301/surrogate_models/utils.py", line 20, in <module>
    from nasbench301.surrogate_models.gnn.gnn import GNNSurrogateModel
  File "/home/ubuntu/naszilla/src/nasbench301/nasbench301/surrogate_models/gnn/gnn.py", line 16, in <module>
    from nasbench301.surrogate_models.gnn.models.deeper_gnn import DeeperGCN
  File "/home/ubuntu/naszilla/src/nasbench301/nasbench301/surrogate_models/gnn/models/deeper_gnn.py", line 8, in <module>
    from nasbench301.surrogate_models.gnn.models.gcn_lib.sparse.torch_nn import norm_layer
  File "/home/ubuntu/naszilla/src/nasbench301/nasbench301/surrogate_models/gnn/models/gcn_lib/sparse/__init__.py", line 1, in <module>
    from .torch_nn import *
  File "/home/ubuntu/naszilla/src/nasbench301/nasbench301/surrogate_models/gnn/models/gcn_lib/sparse/torch_nn.py", line 3, in <module>
    from surrogate_models.gnn.models.gcn_utils.data_util import get_atom_feature_dims, get_bond_feature_dims
ModuleNotFoundError: No module named 'surrogate_models' 
```

**Comment by crwhite14** [comment]
Hi, it looks like this is an error with nasbench301 because the repository was recently updated. There are a couple options to fix it.
(1) If you are only using nasbench101 or nasbench201, then you can comment out lines 8 and 12 of `naszilla/nas_benchmarks.py` for now.
(2) You can make the following changes to the new version of the nasbench301 repository ([this version](https://github.com/automl/nasbench301/commit/48a5f0ca152b83ae2fa31365116c0fb480466fb1)):

- In `nasbench301/surrogate_models/gnn/models/gcn_lib/sparse/torch_nn.py`, line 3, change the line to `from nasbench301.surrogate_models`...

- In `nasbench301/surrogate_models/surrogate_model.py`, line 32, change the line to

`self.config_loader=utils.ConfigLoader(os.path.expanduser('~/nasbench301/configspace.json'))`

- In `nasbench301/surrogate_models/utils.py`, comment out NuSVR/SVR on lines 24-25 and 50-51

I think nasbench301 may be fixed soon, so I will update the naszilla repo when it is fixed.

**Comment by lcmeng** [comment]
Can confirm the suggested changes have fixed the nasbench301 issue, thank you! There're some other issues observed during the test installation. I'll submit them separately. Please feel free to close the issue.
