### ISSUE TITLE
RuntimeError with GCN predictor in installation test

### ISSUE THREAD

**Issue by lcmeng** [naszilla/naszilla#21]
Command: `python naszilla/run_experiments.py --search_space nasbench_101 --algo_params all_algos --queries 30 --trials 1`
Log:

```
...
Finished GP-BayesOpt query 0
Finished GP-BayesOpt query 10

* Running NAS algorithm: {'algo_name': 'gcn_predictor', 'total_queries': 30}
Traceback (most recent call last):
  File "naszilla/run_experiments.py", line 121, in <module>
    main(args)
  File "naszilla/run_experiments.py", line 104, in main
    run_experiments(args, save_path)
  File "naszilla/run_experiments.py", line 52, in run_experiments
    result, val_result, run_datum = run_nas_algorithm(algorithm_params[j], search_space, mp)
  File "/home/ubuntu/naszilla/naszilla/nas_algorithms.py", line 47, in run_nas_algorithm
    data = gcn_predictor(search_space, **ps)
  File "/home/ubuntu/naszilla/naszilla/nas_algorithms.py", line 420, in gcn_predictor
    fit(net, xtrain, seed=seed)
  File "/home/ubuntu/naszilla/naszilla/gcn/train_gcn.py", line 53, in fit
    prediction = net(batch)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/naszilla/naszilla/gcn/model.py", line 66, in forward
    out = layer(out, adj_with_diag)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/naszilla/naszilla/gcn/model.py", line 37, in forward
    output1 = F.relu(torch.matmul(norm_adj, torch.matmul(inputs, self.weight1)))
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_mm
```

This happened on both single-GPU and multi-GPU machines.

**Comment by lcmeng** [comment]
A quick adjacent question: multi-GPU acceleration is currently not considered by the implementation, correct?

**Comment by crwhite14** [comment]
Hi, with the release of nas-bench-301, there is no place in this repository where a GPU is needed. All of the experiments were run on single CPUs, and I would recommend using a CPU.

If you still want to use a GPU instead of a CPU, here is something you can try:
(1) Verify that [this line](https://github.com/naszilla/naszilla/blob/5f5cc534699b401455325f4066003525f3b0a699/naszilla/gcn/train_gcn.py#L18) is printing cuda:0, or replace it with `device = torch.device("cuda:0")`.
(2) Verify that `adj.device` is set to cuda:0 [here](https://github.com/naszilla/naszilla/blob/5f5cc534699b401455325f4066003525f3b0a699/naszilla/gcn/model.py#L64), or else replace that line with `adj_with_diag = normalize_adj(adj + torch.eye(gs, device=torch.device("cuda:0")))`

I think that will work, but it will be a few days before I can check this on a GPU.
